Add standalone/jarmod instructions to the Installing Optifine page
PolyMC/polymc.github.io pull request #212
Opened 2022-09-04 05:55 UTC by Godeps2891

2022-09-05 15:21 UTC, DioEgizio requested changes

2022-09-05 15:21 UTC, DioEgizio commented on src/wiki/getting-started/installing-optifine.md
> +Now in the PolyMC launcher edit the instance you wish to install OptiFine on, open the **Version** tab and on the right click **Add to Minecraft.jar**, select the extracted OptiFine mod(the file endi
```suggestion
Now in PolyMC edit the instance you wish to install OptiFine on, open the **Version** tab and click **Add to Minecraft.jar**, select the extracted OptiFine jarmod (the file ending in \_MOD.jar) and confirm.
```
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/83089242/188480349-c509cd3a-feb9-43a4-a179-2d9442a7ac94.png">

you don't have to right click

2022-09-05 15:21 UTC, DioEgizio commented on src/wiki/getting-started/installing-optifine.md
> +OptiFine will now be copied to and installed as a jarmod for that instance so it is safe to delete the installer and extracted mod.
```suggestion
OptiFine will now be installed as a jarmod in that instance so you can remove the installer and extracted jarmod. 
```

2022-09-05 22:00 UTC, Godeps2891 commented
added all suggested changes

2022-09-08 07:29 UTC, DioEgizio approved these changes

2022-09-13 14:54 UTC, Hans5958 commented on src/wiki/getting-started/installing-optifine.md
> +This method requires you either have the minecraft version you wish to install OptiFine on to be installed through the vanilla launcher or to recreate the folder structure somewhere on your system (l
```suggestion
This method requires you either have the Minecraft version you wish to install OptiFine on to be installed through the vanilla launcher or to recreate the folder structure somewhere on your system (like /.minecraft/versions/*1.18.2*/*1.18.2*.jar).
```

2022-09-18 15:05 UTC, ZekeSmith commented
Looks good to me

2022-09-18 15:05 UTC, merged