New Post
PolyMC/polymc.github.io pull request #224
Opened 2022-10-19 21:57 UTC by JamesQuinley

Message from the team.

2022-10-19 22:07 UTC, JamesQuinley commented
This won't serve to news page, working on that.

2022-10-19 22:07 UTC, Sneedplex requested changes

2022-10-19 22:07 UTC, Sneedplex commented on src/news/what-happened.md
> +A team restructure occured, that unfortunatly lead people to spread false information about the state of our metadata servers
unfortunately@

2022-10-19 22:07 UTC, Sneedplex commented on src/news/what-happened.md
> +title: What happened,and the next step.
space after comma

2022-10-19 23:46 UTC, JamesQuinley commented on src/news/what-happened.md
> +A team restructure occured, that unfortunatly lead people to spread false information about the state of our metadata servers
mb fixing right now

2022-10-19 23:46 UTC, JamesQuinley commented on src/news/what-happened.md
> +title: What happened,and the next step.
Done

2022-10-19 23:52 UTC, JamesQuinley commented
This isn't showing the corrected spacing, will fix once home

2022-10-20 00:02 UTC, Sneedplex requested changes

2022-10-20 00:02 UTC, Sneedplex commented on src/news/what-happened.md
> +A team restructure occured, that unfortunately lead people to spread false information about the state of our metadata servers
led, not lead

2022-10-20 00:03 UTC, Sneedplex commented on src/news/what-happened.md
> +A team restructure occured, that unfortunately lead people to spread false information about the state of our metadata servers
also, occurred, not occured

2022-10-20 00:52 UTC, JamesQuinley commented
Seems the date was formatted incorrectly, that has been fixed and is ready for more review when you get back.

2022-10-21 00:48 UTC, JamesQuinley commented
Sorry messed something up badly, retrying with a clean slate.
Won't make this mistake in the future.

2022-10-21 00:48 UTC, closed without merging